name: Run Vault Setup self-hosted
on: [workflow_dispatch]
jobs:
  Provision:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible
        run: pip-3.11 install ansible
      - name: setup Ansible
        run: echo $PATH
      - name: Run Vault Setup
        run: ansible-playbook -i vault-internal.test.map, tool-setup.yml -e ansible_user=${{ secrets.SSH_USER }} -e ansible_password=${{ secrets.SSH_PASS }} -e tool_name=vault