name: Run Vault Setup
on: [workflow_dispatch]
jobs:
  Provision:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: ${{secrets.AWS_REGION}}

      - run: echo $PATH
      - name: Run Vault Setup
        run: ansible-playbook -i vault-internal.rdevopsb80.online, tool-setup.yml -e ansible_user=${{ secrets.SSH_USER }} -e ansible_password=${{ secrets.SSH_PASS }} -e tool_name=vault

